### PR TITLE
Moved reader mode to page actions #396

### LINKED ISSUE #396: Move reader mode to page actions
It should be toggle switch setting the reader more for entire domain.
It should go under new group called "Domain actions"

### PR DESCRIPTION
**Pull request by shahenAnt**
Fix #396 

## Implementation details
Moved reader mode to page actions.
Reorder page actions.

## Checklist:

- [ ] My squashed commit messages follows the [7 golden rules](https://chris.beams.io/posts/git-commit/)
- [ ] I updated or created necessary unit tests
- [ ] I've tested my changes in Dark Mode, iPad, iOS <= 12, Landscape and in German

### CODE REVIEW

**Comment by chrmod** [comment]
The "page actions button" badge does not go away after navigating to new page 
Screenshot 2019-11-18 at 15 13 32

**Comment by chrmod** [comment]
We can also remove the dark gray circle from behind "page actions button".  How about we move the "badge" a bit up so it does not cover the 3 dots?

**Comment by chrmod** [comment]
Screenshot 2019-11-18 at 15 17 11
Can we remove the white background?

**Comment by shahenAnt** [comment]
@chrmod  I did according changes. Please have a look again.

**Pull request merged**
